In [1]:
from keras.utils import to_categorical
from keras_preprocessing.image import load_img
from keras.layers import Dense,Conv2D, Dropout,Flatten,MaxPooling2D
import os 
import pandas as pd 
import numpy as np

In [2]:
TRAIN_DIR ='C:\\Users\\Des\\Downloads\\archive (4)\\images\\train'
TEST_DIR ='C:\\Users\\Des\\Downloads\\archive (4)\\images\\test - Copy'

In [3]:
import os

print(os.path.exists(TEST_DIR))  # Should return True

True

In [4]:
import os

def createdataframe(dir):
    image_paths = []
    labels = []
    for label in os.listdir(dir):
        for file in os.listdir(os.path.join(dir, label)):
            image_paths.append(os.path.join(dir, label, file))
            labels.append(label)
    return image_paths, labels

In [5]:

train = pd.DataFrame()
train['image'], train['label'] = createdataframe(TRAIN_DIR)
train

                                                  image     label
0     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
1     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
2     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
3     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
4     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
...                                                 ...       ...
6911  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6912  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6913  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6914  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6915  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise

[6916 rows x 2 columns]

In [6]:
print(train)

                                                  image     label
0     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
1     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
2     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
3     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
4     C:\Users\Des\Downloads\archive (4)\images\trai...     angry
...                                                 ...       ...
6911  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6912  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6913  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6914  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise
6915  C:\Users\Des\Downloads\archive (4)\images\trai...  surprise

[6916 rows x 2 columns]

In [7]:

test = pd.DataFrame()
test['image'], test['label'] = createdataframe(TEST_DIR)
test

                                                  image     label
0     C:\Users\Des\Downloads\archive (4)\images\test...     angry
1     C:\Users\Des\Downloads\archive (4)\images\test...     angry
2     C:\Users\Des\Downloads\archive (4)\images\test...     angry
3     C:\Users\Des\Downloads\archive (4)\images\test...     angry
4     C:\Users\Des\Downloads\archive (4)\images\test...     angry
...                                                 ...       ...
6992  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6993  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6994  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6995  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6996  C:\Users\Des\Downloads\archive (4)\images\test...  surprise

[6997 rows x 2 columns]

In [8]:
print(test)

                                                  image     label
0     C:\Users\Des\Downloads\archive (4)\images\test...     angry
1     C:\Users\Des\Downloads\archive (4)\images\test...     angry
2     C:\Users\Des\Downloads\archive (4)\images\test...     angry
3     C:\Users\Des\Downloads\archive (4)\images\test...     angry
4     C:\Users\Des\Downloads\archive (4)\images\test...     angry
...                                                 ...       ...
6992  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6993  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6994  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6995  C:\Users\Des\Downloads\archive (4)\images\test...  surprise
6996  C:\Users\Des\Downloads\archive (4)\images\test...  surprise

[6997 rows x 2 columns]

In [9]:
from tqdm.notebook import tqdm

In [10]:
from tqdm import tqdm
import numpy as np
from tensorflow.keras.preprocessing.image import load_img

def extrat_features(images):
    features = []
    for image in tqdm(images):   # correct variable
        img = load_img(image, color_mode='grayscale', target_size=(48, 48))
        img = np.array(img)
        features.append(img)
    return np.array(features)

In [11]:
color_mode='grayscale'

In [12]:
train_features = extrat_features(train['image'])

100%|██████████| 6916/6916 [00:02<00:00, 3426.30it/s]

In [13]:
test_features = extrat_features(test['image'])

100%|██████████| 6997/6997 [00:02<00:00, 3078.66it/s]

In [14]:
x_train = train_features/255.0
x_test =test_features/255.0

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
le.fit(train['label'])

LabelEncoder()

In [17]:
y_train = le.transform(train['label'])
y_test = le.transform(test['label'])

In [18]:
y_train = to_categorical(y_train,num_classes=7)
y_test = to_categorical(y_test,num_classes=7)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

model = Sequential()

# First block
model.add(Conv2D(128, kernel_size=(3,3), activation='relu', input_shape=(48,48,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

# Second block
model.add(Conv2D(256, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

# Third block
model.add(Conv2D(512, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

# Fourth block
model.add(Conv2D(512, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

# Fully connected layers
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.3))

# Output layer (7 classes)
model.add(Dense(7, activation='softmax'))

# Optional: compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

c:\Users\Des\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 46, 46, 128)    │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 23, 23, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 23, 23, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 21, 21, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 10, 10, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 10, 10, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 8, 8, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 4, 4, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 2, 2, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 1, 1, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 1, 1, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 7)              │         1,799 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,232,199 (16.14 MB)

 Trainable params: 4,232,199 (16.14 MB)

 Non-trainable params: 0 (0.00 B)

In [20]:
metrics='accuracy'

In [21]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [22]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x=x_train,
          y=y_train,
          batch_size=128,
          epochs=50,



          
          validation_data=(x_test, y_test))

Epoch 1/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 479ms/step - accuracy: 0.1630 - loss: 1.9244 - val_accuracy: 0.1628 - val_loss: 1.9038
Epoch 2/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 26s 476ms/step - accuracy: 0.1667 - loss: 1.9161 - val_accuracy: 0.1738 - val_loss: 1.8926
Epoch 3/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 26s 467ms/step - accuracy: 0.1784 - loss: 1.9121 - val_accuracy: 0.1432 - val_loss: 1.8718
Epoch 4/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 26s 465ms/step - accuracy: 0.2063 - loss: 1.8983 - val_accuracy: 0.1429 - val_loss: 1.9028
Epoch 5/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 27s 490ms/step - accuracy: 0.2156 - loss: 1.8840 - val_accuracy: 0.2190 - val_loss: 1.8033
Epoch 6/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 508ms/step - accuracy: 0.2503 - loss: 1.8261 - val_accuracy: 0.2500 - val_loss: 1.7380
Epoch 7/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 515ms/step - accuracy: 0.2728 - loss: 1.7862 - val_accuracy: 0.2873 - val_loss: 1.7407
Epoch 8/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 510ms/step - accuracy: 0.2883 - loss: 1.7529 - val_accuracy: 0.3370 - val_loss: 1.6834
Epoch 9/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 504ms/step - accuracy: 0.3132 - loss: 1.7088 - val_accuracy: 0.2457 - val_loss: 1.8699
Epoch 10/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 505ms/step - accuracy: 0.3195 - loss: 1.7131 - val_accuracy: 0.3370 - val_loss: 1.7005
Epoch 11/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 504ms/step - accuracy: 0.3454 - loss: 1.6558 - val_accuracy: 0.4012 - val_loss: 1.5715
Epoch 12/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 504ms/step - accuracy: 0.3658 - loss: 1.6151 - val_accuracy: 0.3546 - val_loss: 1.6910
Epoch 13/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 505ms/step - accuracy: 0.3796 - loss: 1.6064 - val_accuracy: 0.4303 - val_loss: 1.4779
Epoch 14/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 505ms/step - accuracy: 0.3999 - loss: 1.5538 - val_accuracy: 0.4203 - val_loss: 1.5192
Epoch 15/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 28s 513ms/step - accuracy: 0.4121 - loss: 1.5247 - val_accuracy: 0.4435 - val_loss: 1.4379
Epoch 16/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 31s 571ms/step - accuracy: 0.4213 - loss: 1.4962 - val_accuracy: 0.4386 - val_loss: 1.4809
Epoch 17/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 29s 533ms/step - accuracy: 0.4345 - loss: 1.4606 - val_accuracy: 0.4658 - val_loss: 1.4037
Epoch 18/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 30s 551ms/step - accuracy: 0.4413 - loss: 1.4569 - val_accuracy: 0.4649 - val_loss: 1.4060
Epoch 19/50
55/55 ━━━━━━━━━━━━━━━━━━━━ 44s 798ms/step - accuracy: 0.4575 - loss: 1.4243 - val_accuracy: 0.4458 - val_loss: 1.4524
Epoch 20/50
22/55 ━━━━━━━━━━━━━━━━━━━━ 12s 373ms/step - accuracy: 0.4350 - loss: 1.4352

KeyboardInterrupt:

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - accuracy: 0.5192 - loss: 1.3577
Test Loss: 1.3576747179031372
Test Accuracy: 0.5192224979400635

In [ ]:
from tensorflow.keras.models import load_model

model = load_model("emotion_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
import numpy as np

predictions = model.predict(x_test)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(y_test, axis=1)

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 33ms/step

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(true_classes, predicted_classes))

              precision    recall  f1-score   support

           0       0.45      0.37      0.41       960
           1       0.38      0.64      0.48       111
           2       0.36      0.25      0.29      1018
           3       0.75      0.69      0.72      1825
           4       0.46      0.55      0.50      1216
           5       0.39      0.38      0.39      1139
           6       0.56      0.79      0.66       728

    accuracy                           0.52      6997
   macro avg       0.48      0.53      0.49      6997
weighted avg       0.52      0.52      0.51      6997

In [ ]:
loss='sparse_categorical_crossentropy'

In [ ]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

# Load model
model = load_model("emotion_model.h5")

# Emotion labels (must match your dataset folder order)
emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

def predict_emotion(img_path):
    # Load image
    img = image.load_img(img_path, color_mode='grayscale', target_size=(48, 48))
    
    # Convert to array
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0
    img_array = np.reshape(img_array, (1, 48, 48, 1))

    # Predict
    prediction = model.predict(img_array)
    emotion = emotion_labels[np.argmax(prediction)]

    return emotion

# Example usage
result = predict_emotion("C:\\Users\\Des\\Desktop\\safalta kaushal\\close-up-portrait-gorgeous-young-woman_273609-40846.avif")
print("Predicted Emotion:", result)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Predicted Emotion: Sad

In [ ]:
%pip install pillow pillow-avif-plugin

Requirement already satisfied: pillow in c:\Users\Des\AppData\Local\Programs\Python\Python312\Lib\site-packages (12.1.0)
Requirement already satisfied: pillow-avif-plugin in c:\Users\Des\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.5.5)
Note: you may need to restart the kernel to use updated packages.